### ISSUE TITLE
Little known new features in Rails 6

### ISSUE THREAD

**Issue by benedikt** [ruby-frankfurt/talks#13]
Rails 6 is a major new release with a couple of shiny new features (like ActionText). However, if you're like me, you're way more excited about some of the less flashy changes in this release. I'd love to share some of them and hear about your favorites.

**Comment by klaustopher** [comment]
Would you be able to do this this meetup? ;)

**Comment by benedikt** [comment]
Yes, let's do it! :)

**Comment by klaustopher** [comment]
@benedikt can you link the slides? :)

**Comment by benedikt** [comment]
@klaustopher Here you go: [Little known Rails 6 features.pdf](https://github.com/ruby-frankfurt/talks/files/3661972/Little.know.Rails.6.features.pdf)
