### ISSUE TITLE
Test Coverage (in Ruby)

### ISSUE THREAD

**Issue by klyonrad** [ruby-frankfurt/talks#15]
This idea of mine for a talk is totally not fleshed out, so it's more like a topic.

In the past years I have observed various stuff regarding test coverage and also built up some opinions. So I thought it could be fun to have a 10-15 minute presentation about code coverage and afterwards get into a **heated** discussion 🔥

With enough interest (expressed through emojis and or comments) I might get motivated enough to do this in the spring 2020 😁

**Comment by FlowFX** [comment]
I like it. @klaustopher and I will have strong opinions as well. Should make for a good discussion.

**Comment by klyonrad** [comment]
I finally managed to present this yesterday!

Here are the slides that I used

[ruby_test_coverage_luka.pdf](https://github.com/ruby-frankfurt/talks/files/9887631/ruby_test_coverage_luka.pdf)
https://www.dropbox.com/s/e4d1e9ktbz54al0/ruby_test_coverage_luka.key?dl=0

The references that I mentioned there for easier clicking:

- Michael Grosser: https://grosser.github.io/ruby-coverage-talk
- Jemma Issroff: https://jemma.dev/blog/ruby-code-coverage
- Kevin Murphy: https://kevinjmurphy.com/posts/rubys-got-you-covered/
  - Enough Coverage to beat the band https://www.youtube.com/watch?v=EyLO0EEm3BQ
- Kostis Capelonis: https://blog.codepipes.com/testing/software-testing-antipatterns.html#anti-pattern-6---paying-excessive-attention-to-test-coverage 
- https://www.gitclear.com/popular_software_engineering_metrics_and_how_they_are_gamed#test-coverage
