### ISSUE TITLE
The Lost Art of Single File Ruby Programs

### ISSUE THREAD

**Issue by fabrik42** [ruby-frankfurt/talks#16]
Hi! This is just an idea that has been spooking in my head for the last week.

Ruby and its ecosystem provide a couple of nice tools to organize logic and/or data in a single file.

I would like to show you some nifty features you may have not known of yet. How they can be used in practical ways, but also in weird and funny ways.

**Comment by benedikt** [comment]
Love it!

**Comment by fabrik42** [comment]
I think I could do it for March. Right now I would assume it will be a 20-30min talk :)

**Comment by bogn83** [comment]
Cool, discussed with @fabrik42 that this will happen in March. Looking forward to it.

**Comment by klyonrad** [comment]
@fabrik42 Would you like to upload your slides here and/or link to the youtube video that you made another time. This was an amazing talk ❤️

**Comment by fabrik42** [comment]
Thanks :) 

You can find all the assets here: https://github.com/fabrik42/single-file-ruby-programs (code, presentation, video)
