### ISSUE TITLE
Proposal: Rails 7 + 7.1 (upcoming)

### ISSUE THREAD

**Issue by zealot128** [ruby-frankfurt/talks#17]
https://www.stefanwienert.de/blog/2021/08/24/upcoming-rails-7-changes-active-record/

Already talked about it on a Ruby Rogues podcast episode :) 

- Zeitwerk
- Encryption
- load_async
- The Whole Asset Story (import maps, jsbundling, cssbundling)/Webpacker migration
- Active Storage predefined variants
- Model convenience stuff

Previewing new Rails 7.1 stuff (which should be probably released this year):
- password_challenge, generates_token_for, authenticate_by
- CTE support, select uses hash syntax
- erb locals definition
- unused routes
- TBD

How to upgrade rails
- https://railsdiff.org/
- rails app:update
- new_framework_defaults / load_defaults

Discussion: 
- How or when do you upgrade Rails (regular process?), [nextRails](https://github.com/fastruby/next_rails)
- How many are using Rails 7, 6.1, 6.0 or older in prod
- Biggest obstacles in the past or present

**Comment by klyonrad** [comment]
@zealot128 This is a proposal, right? In the sense that you would be interested in holding a talk about these topics?

**Comment by zealot128** [comment]
> @zealot128 This is a proposal, right? In the sense that you would be interested in holding a talk about these topics?

Yes, that's right. As i am not a contributor/committer, I could not assign the labels myself.

**Comment by zealot128** [comment]
The slides are here:

- https://documents.pludoni.de/p/Sj34Cliy7#/
- PDF (unfortunately, the links to not work in this pdf) 
[Rails 7 & 7.1pre Features - CodiMD.pdf](https://github.com/ruby-frankfurt/talks/files/10507219/Rails.7.7.1pre.Features.-.CodiMD.pdf)
- Daily updated Rails changelog viewer: https://zealot128.github.io/rails-changelog

**Comment by fabrik42** [comment]
Thank you!
This was a nice talk :)

**Comment by klyonrad** [comment]
@zealot128 Looks like there is a setting missing at the moment

> You are not allowed to access this page. Maybe try logging in?

**Comment by zealot128** [comment]
@klyonrad should work now! Didn't know the presentation is also private by default in Hackmd.
