### ISSUE TITLE
Hanami 2.0 (2.1)

### ISSUE THREAD

**Issue by tonklon** [ruby-frankfurt/talks#19]
Hanami is a full application framework for ruby. https://hanamirb.org

It takes a different approach then Rails. It relies (as of 2.0) on the dry-rb group of gems.

It would be interesting to explore the differences and opportunities this allows for application structure. I have not used hanami, yet, but proposing a talk is a nice way to force myself doing so.

Although I recommend to wait for the 2.1 release (due in Q1/2023) when rom-rb will be integrated as persistence layer.

**Comment by klyonrad** [comment]
@tonklon Would the Tuesday, the 28th of March work for you?

**Comment by kevkev300** [comment]
Hi @tonklon, just wanted to ask again if Tuesday, 28th of March would work for you?

**Comment by tonklon** [comment]
Hi guys, sorry I did not receive information about your question. I guess I need to check my notification settings.

Nevertheless, Hanami 2.1 ist still not out, and I wanted to wait for it.

**Comment by tonklon** [comment]
Hanami 2.1 is out now. I did not yet have time to really look into it, but I still like to do so, and tell all of you something about what differentiates it from Rails.

**Comment by kevkev300** [comment]
that sounds amazing!
The next Meetup will be in September, so there is some time until then 😄 

What do you think, will that work for you?

**Comment by bogn83** [comment]
Hi @tonklon, hope you had a good summertime. Would you be ready and willing to give the Hanami talk on the 26th or 27th of September and if so is there a significant preference?

**Comment by kevkev300** [comment]
So, sorry for the short notice:

For now, we will go with this talk: https://github.com/ruby-frankfurt/talks/issues/23 as he already gave it at a conference. So, the preparation is not on such a short notice.

The next meetup will be in the end of November, what about then?

**Comment by tonklon** [comment]
Hi @bogn83 , @kevkev300.

Hanami 2.1 is still not finished (see https://github.com/orgs/hanami/projects/2 ) But I think enough of it is done, to make a meaningful talk. I will check in the next days.

I guess November should really work.

**Comment by bogn83** [comment]
Thanks for the heads-up. Looking forward to it.

**Comment by kevkev300** [comment]
Thanks! I'm curious :)

**Comment by tonklon** [comment]
@bogn83 @kevkev300 Im planning to prepare this for November. Do we have a date already? The 23rd would not work for me.

**Comment by kevkev300** [comment]
@tonklon , sorry we somehow missed scheduling for this week but plan to schedule one for next week Wednesday, Dec. 6th. Would that work for you?

We would also be open to do the 11th :)

**Comment by kevkev300** [comment]
Hi @tonklon, just asking again to send another notification 😆

**Comment by tonklon** [comment]
Hi @kevkev300 the 6th won't work. But the 11th should work for me.
My colleague would Linkliste not be there for reporting on RailsWorld.
Let's see....

**Comment by kevkev300** [comment]
Hi @tonklon , sorry for coming back to you so late. I will do a final location check and if everything works, I publish it tomorrow.

> My colleague would Linkliste not be there for reporting on RailsWorld.

I don't get it 😅  Do you mean your colleague will probably **not** be there for reporting on RailsWorld? So no RailsWorld talk, right? (Actually, I totally forgot that we talked about this 🙈 so, all good )

**Comment by kevkev300** [comment]
Hi @tonklon , we're set for December 11th :)
I will publish it this morning

**Comment by tonklon** [comment]
Great!

**Comment by kevkev300** [comment]
@tonklon do you want to upload your slides as well? Would be really cool!

**Comment by tonklon** [comment]
@kevkev300 Yes, thanks for the reminder. Where to put them?

**Comment by kevkev300** [comment]
> @kevkev300 Yes, thanks for the reminder. Where to put them?

For my last talk I just drag and dropped the power point into a comment within the talk issue 😅 You can also add it to an online presenter tool (like https://speakerdeck.com/) and then just post the link here
