### ISSUE TITLE
Rake

### ISSUE THREAD

**Issue by klyonrad** [ruby-frankfurt/talks#20]
I don't have a title for this, but based on crazy flaky-test issue that I solved in the past half year I could imagine having a talk about 

## Rake Tasks

This topic is also a fall back option when there is the lack of other topics.

Please feel free to add ideas or questions in the comments :)

**Comment by kevkev300** [comment]
hey @klyonrad, are you still up to the topic and want to present it? :)

**Comment by klyonrad** [comment]
Unfortunately no, difficult with the lack of time

Also don't fully remember anymore what issue I meant 😁
