### ISSUE TITLE
REST in Peace (GraphQL for realz)

### ISSUE THREAD

**Issue by we5** [ruby-frankfurt/talks#21]
Hi there,

wonder if there is  any interest in talking about some GraphQL stuff? We are currently in the final stage of re-implementing a former REST API into some fancy GraphQL service. It’s used to power a single Flutter app, so it is not necessarily a public API.

We‘ve learned a lot and and are still learning. But generally speaking I am really satisfied with the outcome, especially with regards to the toolchain and documentation.

And I also want to hear opinions and talk about dramas and learnings with others. 

I am not entirely sure if I will manage to have some nice presentation already for the upcoming march meetup but see it more as a general question

**Comment by kevkev300** [comment]
Hi @we5 , I think in general that is definitely interesting :)
As the March meetup is closer, do you think you could prepare the talk by then (28th of March)?

**Comment by we5** [comment]
Hey @kevkev300, thanks for the question. 

I would really love to, however because of this week's work-load and some out-of-office appointments I have not so much time to really prepare something great I think. What is the usual duration and information you get for the talks? Maybe i can have a very quick run down of some pros and cons ...

**Comment by kevkev300** [comment]
Hi @we5,

I believe it's around 15-30 minutes.
You can decide whatever you feel it's best. I'm also thinking about maybe not needing to have a talk but rather a discussion with a small lightning talk to kick it off and maybe some prepared questions to discuss.

So, in the end, it does not have to be a big talk, just whatever format you think fits to the topic (also open to other format ideas 😄 ).

**Comment by we5** [comment]
@kevkev300 

I already started some slides ;)
My goal is to have a quick overview and more of a shorter talk and more time to discuss and maybe also show some  examples from the real world (the actual project).

I am definitely not an established expert in GraphQL (it is my first project using this for the server side) so I also look for other opinions and examples, especially when it comes to scaling and security.

So let’s do this. 
If, for any reason, I have problems finishing it, I will let you know as soon as possible.

**Comment by benedikt** [comment]
@we5 Awesome! Looking forward to see you again (for the first time in ages).

**Comment by kevkev300** [comment]
@we5 amazing! Thanks and I'm looking forward to it :)

**Comment by we5** [comment]
Hey,

I think I have some good starter slides but I will have to finish fast and promptly because of not enough time to do a proper storyline.

However I think it will be a good foundation to talk and discuss the topic.

See you!

**Comment by kevkev300** [comment]
@we5 all good, I bet it will be great :)

**Comment by kevkev300** [comment]
@we5 sorry for the late reaching out. If you want you can link your slides here and I can promote them via Mastodon :)
