### ISSUE TITLE
Deeper look into the ruby-openai gem

### ISSUE THREAD

**Issue by Nookbe** [ruby-frankfurt/talks#22]
![ai_expert_meme](https://user-images.githubusercontent.com/36129177/233307349-34cba133-6ca2-440a-8729-8bf4d0c445f6.jpeg)

In expectation of getting roasted on stage, I could present the openai gem and take a deeper look into it.
Also presenting some use cases for it. I have not yet digged super deep into it but to quote another host here: "proposing a talk is a nice way to force myself doing so".

**Comment by kevkev300** [comment]
thanks for the proposal @Nookbe !
As discussed we're happy to have you on board for the June 7th meetup 🚀
