### ISSUE TITLE
Hotwire: Turbo

### ISSUE THREAD

**Issue by kevkev300** [ruby-frankfurt/talks#25]
I will try to give an overview over the changes in turbo 8 and how to move from Turbo 7 to Turbo 8, highlighting differences and so on. If time permits, I want to dive a bit into Strada ("Create fully native controls, driven by your web app.") as well.

**Comment by kevkev300** [comment]
@benedikt @bogn83 
I would offer to do this talk in the next meetup, what do you think?

**Comment by kevkev300** [comment]
testing slack integration

**Comment by kevkev300** [comment]
test slack integration 2

**Comment by benedikt** [comment]
@kevkev300 Sounds great!

**Comment by kevkev300** [comment]
Here is my presentation: 
[Hotwire 8 & Strada.pptx](https://github.com/ruby-frankfurt/talks/files/14112264/Hotwire.8.Strada.pptx)

And here is the example's app repo: https://github.com/kevkev300/personal_knowledge_base

I will hold the strada part in the next meetup: https://github.com/ruby-frankfurt/talks/issues/27
