### ISSUE TITLE
You are manipulating URLs? You're probably doing it wrong.

### ISSUE THREAD

**Issue by tonklon** [ruby-frankfurt/talks#28]
aka. Common pitfalls working with URLs.

As most of us are working in web development we deal with URLs all the time. Sometimes we also do manipulate URLs: attaching a path component, Getting the base path.
In these cases we often see `.split("/")` or `.join("/")`. Let me show you some of the problems, that can arise doing this and some ways to ensure URLs remain sane.

Includes view into other languages and how URLs are handled there, as I think ruby is a little lacking here.

Thias talk will work well as a half hour version, but could be extended to fill the evening if nessesary.

**Comment by kevkev300** [comment]
@tonklon , cool topic!
We're thinking about the 16.04. for the next meetup. Would that work for you?

**Comment by tonklon** [comment]
I have to check.

**Comment by kevkev300** [comment]
@tonklon alright :)
We just announced the Ruby Meetup where we currently have one talk about Turbo Native & Strade (by me as I promised it last time)

So, having your talk as a short one would perfectly still fit :)

**Comment by kevkev300** [comment]
@tonklon 
Do you know already if it would work on the 16th?

**Comment by tonklon** [comment]
@kevkev300 Yes, it will.

**Comment by kevkev300** [comment]
@tonklon amazing, then it is scheduled 😄 
Thank you!

**Comment by tonklon** [comment]
This talk was held on 04-16-2024 @ portagon
