### ISSUE TITLE
Packs / Packwerk intro talk

### ISSUE THREAD

**Issue by zealot128** [ruby-frankfurt/talks#29]
As a reference:

Online presentation:
- https://documents.pludoni.de/p/W1UEIyiP5#/

As PDF rendered:
- [Rails “Packs” - CodiMD.pdf](https://github.com/user-attachments/files/15881055/Rails.Packs.-.CodiMD.pdf)

was performed on 2024-06-17

**Comment by chb-ioki** [comment]
Just read through the slides. Very cool! Thank you for sharing!

**Comment by fabrik42** [comment]
Just read through the slides. Very cool! Thank you for sharing!

**Comment by zealot128** [comment]
I made a blog post from the content + additional recipes for better consumption.

https://www.stefanwienert.de/blog/2024/06/23/using-packs-a-k-a-packwerk-as-code-organization-engine-alternative/
