### ISSUE TITLE
[request] Transforming Rails apps to (almost) API only

### ISSUE THREAD

**Issue by klyonrad** [ruby-frankfurt/talks#3]
The `api_only` option has been around in the Rails world for quite some time but before that a lot of applications have been created by using lots of the rails frontend capabilities.

Even though it might become anecdotal it could be interesting to hear about actual examples of converting an existing app to the API way and give details about the Pros and Cons, the hiccups, the pitfalls but also the exciting stuff about it.

**Comment by fabrik42** [comment]
Hmm I think I have some interesting war stories about this, but I am not sure if I can make it to the next meetup 😕

**Comment by klaustopher** [comment]
I think we might move this talk to the November meetup if this is possible and let @klyonrad give the talk #2 this time. I'm also really interested in this one ;)

**Comment by klaustopher** [comment]
@fabrik42 will do this ;)
