### ISSUE TITLE
[proposal] RemoteRuby - running ruby code on remote machines from local scripts.

### ISSUE THREAD

**Issue by Nu-hin** [ruby-frankfurt/talks#4]
Presenting a remote_ruby gem, which allows for running Ruby code on remote machines from local code.

More info here: https://github.com/Nu-hin/remote_ruby

The talk should be 10-15 minutes, plus answering questions, if there will be any.

**Comment by klaustopher** [comment]
Would it be possible to prepare the talk for this thursday?

**Comment by Nu-hin** [comment]
Well, actually I thought we are collecting talks for Thursday 😄 Yes.

**Comment by klaustopher** [comment]
Then you are in ;)
