### ISSUE TITLE
Modular and composable services with Dry gems;

### ISSUE THREAD

**Issue by timgluz** [ruby-frankfurt/talks#5]
I would like to talk about [Dry gems](https://dry-rb.org/gems/) - there're way too many great gems, 
that's why i will take a bit narrower scope and build example service for a `Pizza as Service`, which would cover 5 most important gems : `dry-transaction, dry-initializer, dry-validator, dry-events & dry-monads`. 

The talk would cover:

1. how to check correctness of input data (type safety and validation for dynamic language) 
2. compose multiple services into a flow, s.o Rail-way pattern (includes M-word)
3. reacting to events on each step of flow (GOF's Observable pattern in Action)

I guess it would take 30min and i would be ready to give talk in December/Januar;

What's your opinion?

**Comment by klaustopher** [comment]
Yes, that's a great topic, and I think it's always good to tell more people about the existance of those gems ;) On Thursday we will discuss the schedule for the next year. I think the next meetup will be in January or February, so I will let you know ;)

**Comment by fabrik42** [comment]
Cool topic! I would love to see this talk! 👍

**Comment by FlowFX** [comment]
Love it! We've recently started to use `dry-transaction` to build services. But I still don't understand how to compose multiple services or re-use step methods.

**Comment by klaustopher** [comment]
@timgluz are you still up to do this at the march meetup?

**Comment by timgluz** [comment]
@klaustopher yes, then I'll back from vacation and I have finished the demo.

**Comment by FlowFX** [comment]
Link to demo files: https://github.com/timgluz/dryrb_talk
