### ISSUE TITLE
Coderetreat

### ISSUE THREAD

**Issue by fabrik42** [ruby-frankfurt/talks#6]
Either for the [Global Day of Coderetreat](https://www.coderetreat.org/) or just at any other date, we could do a more practical meetup, where everyone gets the same (rather simple) problem, solves it and presents the solution to the rest.

Ruby is a very flexible language and doing this, we could learn a lot of different ways how to solve the same problem.

**Comment by benjmin-r** [comment]
I could help facilitate a Coderetreat or a similar event. I've done quite a few of those some years back.

**Comment by klyonrad** [comment]
As a matter of fact, there will be a Code Retreat event next week Saturday! https://www.eventbrite.com/e/global-day-of-coderetreat-2022-frankfurt-portagon-tickets-438970080327
