### ISSUE TITLE
RSpec for pytest lovers

### ISSUE THREAD

**Issue by FlowFX** [ruby-frankfurt/talks#7]
Before I started working with Rails in 2018 I worked with Django. Django comes with Python, and Python comes with pytest, and there’s nothing better than pytest. Certainly not RSpec.

I have since developed a love-hate attitude towards RSpec that I would like to explore in this talk.

- Anti-patterns that I learned from the existing code base
- Better patterns that I have learned from other resources
- Things I’m still missing that make pytest so great

This will hopefully be both, an informative talk and a discussion about best practices in testing Rails application.

Or maybe it won’t, but I’ll try.

**Comment by klaustopher** [comment]
Could you do that one this month? ;)

**Comment by klaustopher** [comment]
Sorry for not reacting sooner

**Comment by FlowFX** [comment]
Sure.

**Comment by FlowFX** [comment]
5 Invites to chaos.social: https://chaos.social/invite/mJGk5adP
