### ISSUE TITLE
Vim tricks for Rails

### ISSUE THREAD

**Issue by FlowFX** [ruby-frankfurt/talks#9]
I want to show a few Rails-related Vim tricks I have picked up during the last year. Afterwards I'd like to start a discussion about what other tricks and tools people use every day, independent of their editor or IDE.

```
#vim-test #rspec-rails #tslime #vim-rails
```

**Comment by FlowFX** [comment]
@klaustopher Is this a go for next week? I'm happy to postpone it. 😬 

In any case, it's not going to be **a lot** of content, but I'm hoping to start a fruitful discussion about tools. 

I'd just need to know so I can prepare.

**Comment by klaustopher** [comment]
Since nobody else offered something, that would be cool ;)

Discussion starter is amazing. I think I will also prepare the deployment talk.

Von meinem iPhone gesendet

**Comment by FlowFX** [comment]
> I think I will also prepare the deployment talk.

Please do. 😃
